name: Update Metrics

on:
  schedule:
    - cron: '0,30 * * * *' # Set your desired schedule, this example runs every hour

jobs:
  update_metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Metrics Embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.TOKEN }}
